### ISSUE TITLE
Obsolete Activity Streams Identifiers

### ISSUE THREAD

**Issue by fugu13** [IMSGlobal/caliper-contexts-public#1]
The context uses http://activitystrea.ms/2.0/ as the Activity Streams 2.0 prefix, which was the URL in a very early draft of the specification. The URL was changed to http://www.w3.org/ns/activitystreams# last year, I think in November, well before Activity Streams 2.0 was finalized.

Also, at least some of the terms used seem to be based on the outdated draft. Most notably, the "action" attribute maps onto activity streams' "verb", except, per the AS 2.0 spec:

> Previous versions of the Activity Streams format used the verb property to identify the action type. The verb must not be used within an Activity Streams 2.0 Activity to represent the action type.

**Comment by vineet-sinha** [comment]
@fugu13 - thanks for flagging this. We will discuss these during our meeting next week and fix them.

**Comment by arwhyte** [comment]
Closing.  Caliper 1.1.0 JSON-LD context does not reference Activity Stream terms.
